version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    ports:
      - "8888:8888"
    volumes:
      - ./api:/api
    networks:
      - Sauron

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    hostname: bot
    volumes:
      - ./bot:/bot
    networks:
      - Sauron

networks:
  Sauron:
    driver: bridge