version: "3.7"

networks:
  Sauron:
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    ports:
      - "8888:8888"
    volumes:
      - ./api:/api
    networks:
      Sauron:
        ipv4_address: 172.18.0.12
    environment:
      - HETZNER_UTILS_IP=${HETZNER_UTILS_IP}

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - api
    container_name: bot
    hostname: bot
    volumes:
      - ./bot:/bot
    networks:
      Sauron:
        ipv4_address: 172.18.0.13
